name: core
description: Core infrastructure for the Flutter app
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.0  # Для HTTP-запросов
  retrofit: ^4.0.0  # Для code generation API
  logger: ^2.0.0  # Для логирования
  get_it: ^7.6.0  # Для DI
  injectable: ^2.4.0  # Для code generation DI
  config:
    path: ../config  # Для доступа к AppConfig (baseUrl)

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0  # Для моков в тестах
  build_runner: ^2.4.0
  retrofit_generator: ^4.0.0
  injectable_generator: ^2.4.0
