name: products
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core

    
  widgets:
    path: ../../shared/widgets

  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  mockito: ^5.4.6
  build_runner: ^2.10.5

flutter:
