name: config
description: Global configuration for the Flutter app
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0  # Для загрузки .env
  intl: ^0.18.0  # Для локализации
  firebase_remote_config: ^4.0.0  # Для feature flags
  get_it: ^7.6.0  # Для DI
  injectable: ^2.4.0  # Для code generation DI

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  injectable_generator: ^2.4.0