name: app
description: A large-scale Flutter application
publish_to: 'none'

version: 1.0.0
environment:
  sdk: ^3.9.2
workspace:
  - packages/core
  - packages/platform/di
  - packages/platform/client
  - packages/platform/logger
  - packages/platform/router
  - packages/platform/storage
  - packages/features/products
  - packages/features/basket

dependencies:
  flutter:
    sdk: flutter

  core:
    path: packages/core
  di:
    path: packages/platform/di
  client:
    path: packages/platform/client
  logger:
    path: packages/platform/logger
  router:
    path: packages/platform/router
  storage:
    path: packages/platform/storage
  products:
    path: packages/features/products
  basket:
    path: packages/features/basket

dev_dependencies: 
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  build_runner: ^2.10.5

flutter:
  uses-material-design: true