name: auth
description: Authentication feature for the Flutter app
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  freezed_annotation: ^2.4.0
  get_it: ^7.6.0
  injectable: ^2.4.0
  dartz: ^0.10.0
  shared:
    path: ../shared
  core:
    path: ../core
  config:
    path: ../config

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  build_runner: ^2.4.0
  freezed: ^2.4.0
  injectable_generator: ^2.4.0
